### ISSUE TITLE
VPC Network Firewall rule

### ISSUE THREAD

**Issue by jessequinn** [turbot/steampipe-mod-gcp-compliance#62]
Currently the control 2.7 states

```
resource.type="gce_firewall_rule"
AND protoPayload.methodName="v1.compute.firewalls.patch" OR protoPayload.methodName="v1.compute.firewalls.insert"
```

however, in reality the correct filter is:

```
resource.type="gce_firewall_rule"
AND protoPayload.methodName="beta.compute.firewalls.patch" OR protoPayload.methodName="beta.compute.firewalls.insert"
```

**Comment by cbruno10** [comment]
Hey @jessequinn , thanks for reporting this issue! In CIS v1.2.0, which is the current benchmark we have implemented, the filter does use the `v1.compute` method name instead of `beta.compute`, so because we stick to what the benchmark recommends exactly, we wouldn't change our control for CIS v1.2.0 controls.

However, I do see that there is now CIS v1.3.0 for GCP, so as we implement that over the upcoming weeks, we'll see if control 2.7 has the updated query or not.

**Comment by jessequinn** [comment]
thanks. i viewed the new cis 1.3 and my team will update to these new filters. They do not contain the beta. but rather compute.... Thanks.
